import { IsEthereumAddress, IsNotEmpty, IsString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class VerifySignatureDto {
  @ApiProperty({ description: 'The Ethereum address of the user', example: '0x1A2b3C4d5E...' })
  @IsNotEmpty()
  @IsEthereumAddress()
  publicAddress: string;

  @ApiProperty({ description: 'The signature generated by signing the message', example: '0xabc123...' })
  @IsNotEmpty()
  @IsString()
  signature: string;

  @ApiProperty({ description: 'The original message that was signed', example: 'Sign in to Aegis with nonce: 12345' })
  @IsNotEmpty()
  @IsString()
  message: string;
}
